openapi: 3.0.3
info:
  title: conduktor-coding-challenge
  version: 1.0.0
paths:
  /clusters:
    get:
      operationId: listClusters
      responses:
        '200':
          description: List the clusters available
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cluster'
        default:
          description: ''
    post:
      operationId: createCluster
      requestBody:
        description: Friendly name of the cluster to create
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: ''
        default:
          description: ''
  /clusters/{id}:
    delete:
      operationId: deleteCluster
      parameters:
        - name: id
          in: path
          description: ID of the cluster to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
        default:
          description: ''
  /clusters/{id}/topics:
    get:
      operationId: listTopics
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of the topics for this cluster
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'
        default:
          description: ''
    post:
      operationId: createTopic
      parameters:
        - name: id
          in: path
          description: Cluster ID
          required: true
          schema:
            type: string
      requestBody:
        description: Name of the topic to create
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: ''
        default:
          description: ''
  /clusters/{id}/topics/{topic}/data:
    get:
      operationId: getData
      parameters:
        - name: id
          in: path
          description: Cluster ID
          required: true
          schema:
            type: string
        - name: topic
          in: path
          description: Name of the topic to fetch data from
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Data from the topic
          content:
            text/event-stream:
              schema:
                type: string
                format: binary
        default:
          description: ''
components:
  schemas:
    Cluster:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Topic:
      required:
        - name
      type: object
      properties:
        name:
          type: string
